### ISSUE TITLE
the master not join on cluster if it is recreated (empty)

### ISSUE THREAD

**Issue by dottgonzo** [arun-gupta/docker-images#12]
Hi,
running a master + replicas, give the opportunity to have a failover system. In my cluster i've tried to remove and recreate the master and i was expecting to see that it came back in the cluster and recover it's data, but this not happen. Can you help me to understand if it is doable?

this is my compose

```
version: '3.3'

networks:
  traefik-net:
    external: true
  couchdb:
    external: true

services:

  master:
    image: arungupta/couchbase
    networks:
      - traefik-net
      - couchdb
    environment:
      TYPE: MASTER
    deploy:
      labels:
        - traefik.port=11211
        - traefik.frontend.rule=Host:couchdb.XXXXXX
        - traefik.docker.network=traefik-net
        - traefik.cluster.port=8091
        - traefik.cluster.frontend.rule=Host:couchadmin.XXXXX
        - traefik.cluster.docker.network=traefik-net
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 5s

  replicas:
    image: arungupta/couchbase
    networks:
      - couchdb
    environment:
      TYPE: WORKER
      COUCHBASE_MASTER: couchdb_master
      AUTO_REBALANCE: 'true'
    deploy:
      mode: global
      endpoint_mode: dnsrr
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 5s

```
